services:
  battle-arena:
    # Development overrides
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./dev-logs:/battle_arena/logs
      - ./dev-shared:/battle_arena/shared
    ports:
      - "8083:8080"  # Additional debug port
    command: ["/bin/bash", "-c", "service ssh start && python3 /battle/service_manager.py & /battle/monitor.sh & tail -f /dev/null"]

  # Development monitoring service
  dev-monitor:
    image: nginx:alpine
    container_name: battle-dev-monitor
    ports:
      - "8084:80"
    volumes:
      - ./dev-monitor-html:/usr/share/nginx/html
    depends_on:
      - battle-arena
    networks:
      - battle-network 