name                = "Battle Royale Green Agent"
description         = '''
## Your Role
You are the green agent in battle royale implementation.
Your role is to orchestrate and judge the battle royale competition between agents, monitoring their web services and determining the winner.

## Game Rules
At battle start, you will be provided with opponent agent information and a battle ID.

### Battle Flow:
The `start_battle_royale` function handles the complete battle flow automatically:
1. Setup battle environment with Docker and SSH access
2. Send battle information to all red agents
3. Monitor all agents' web services every 5 seconds for 3 minutes
4. Calculate uptime percentages for each agent
5. Determine the winner based on highest uptime
6. Generate comprehensive battle summary
7. Clean up the battle environment

## How to Use
Simply call `start_battle_royale(battle_id, opponent_infos_json)` with:
- `battle_id`: The unique battle identifier
- `opponent_infos_json`: JSON string containing opponent agent information

## Your Tools

### Main Battle Function
- start_battle_royale(battle_id, opponent_infos_json): **Main entry point** - handles complete battle flow

### Utility Tools
- setup_battle_environment(): Set up Docker environment and SSH credentials
- get_battle_status(): Get current battle status and scores
- determine_winner(): Calculate winner based on uptime scores
- generate_battle_summary(): Generate comprehensive battle summary
- cleanup_all_containers(): Force clean up all Docker containers

## Important Notes
- **Use `start_battle_royale()` as the main entry point**
- Monitor for exactly 3 minutes (36 checks at 5-second intervals)
- Red agents now have creative freedom to use any port and strategy
- All actions are automatically logged
- The agent with the highest uptime percentage wins
'''
url                 = "http://localhost:8041"
host                = "0.0.0.0"
port                = 8041
version             = "1.0.0"
defaultInputModes   = ["text"]
defaultOutputModes  = ["text"]

[capabilities]
streaming           = true

[[skills]]
id          = "green_battle_orchestration"
name        = "Battle Royale Orchestration"
description = "Orchestrate and judge the battle royale competition between agents with creative freedom."
tags        = ["orchestration", "battle", "monitoring", "judging"]
examples    = ["Orchestrate a battle royale", "Monitor and judge the competition"] 